USE homework--切换数据库

----查询(1)
SELECT DISTINCT SNO
FROM SPJ
WHERE JNO='J1';

----查询(2)
SELECT DISTINCT SNO
FROM SPJ
WHERE JNO='J1' AND PNO='P1';

----查询(3)
SELECT DISTINCT SNO
FROM SPJ, P
WHERE SPJ.PNO=P.PNO AND --连接谓词
    JNO='J1'AND P.COLOR = '红';--限定条件

----查询(4)
    SELECT DISTINCT JNO
    FROM J
EXCEPT
    SELECT DISTINCT JNO
    FROM SPJ, S , P
    WHERE SPJ.SNO=S.SNO AND SPJ.PNO=P.PNO AND--连接谓词
        S.CITY = '天津' AND P.COLOR = '红';--限定条件

----查询(5)
SELECT DISTINCT JNO
FROM SPJ SPJ1
WHERE NOT EXISTS(   
    SELECT *
FROM SPJ SPJ2
WHERE SPJ2.SNO='S1' AND
    NOT EXISTS(   
        SELECT *
    FROM SPJ SPJ3
    WHERE SPJ3.JNO=SPJ1.JNO AND
        SPJ3.PNO=SPJ2.PNO));



