USE homework--切换数据库

----查询(1)
SELECT DISTINCT S.SNAME, S.CITY
FROM S;

----查询(2)
SELECT DISTINCT P.PNAME, P.COLOR, P.WEIGHT
FROM P;
----查询(3)
SELECT DISTINCT SPJ.JNO
FROM SPJ
WHERE SPJ.SNO='S1';
----查询(4)
SELECT DISTINCT P.PNAME, SUM(SPJ.QTY)
FROM SPJ, P
WHERE SPJ.PNO = P.PNO AND
    SPJ.JNO='J4'
GROUP BY P.PNAME;
----查询(5)
SELECT DISTINCT SPJ.PNO
FROM SPJ, S
WHERE SPJ.SNO=S.SNO AND
    S.CITY='上海';
----查询(6)
SELECT DISTINCT SPJ.JNO
FROM SPJ, S
WHERE SPJ.SNO=S.SNO AND
    S.CITY='上海';
----查询(7)
SELECT DISTINCT SPJ1.JNO
FROM SPJ SPJ1
WHERE  NOT EXISTS(
    SELECT *
FROM SPJ SPJ2, S
WHERE SPJ2.SNO = S.SNO AND
    SPJ2.JNO=SPJ1.JNO AND
    S.CITY='天津');
----查询(8)
UPDATE P
SET COLOR='蓝'
WHERE COLOR='红';
SELECT *
FROM P;
----查询(9)
UPDATE SPJ
SET SNO='S3'
WHERE SNO='S5'AND
    JNO='J4'AND
    PNO='P6';
SELECT * FROM SPJ;
----查询(10)
DELETE FROM SPJ
WHERE SNO='S2';
DELETE FROM S
WHERE SNO='S2';
SELECT * FROM S;
SELECT * FROM SPJ;
----查询(11)
INSERT INTO SPJ
VALUES('S2','P4','J6',200);
SELECT * FROM SPJ;