--FILM(FID int, FNAME char(30), FTYPE char(10), DNAME char(30), length int, IS3D char(1)，GRADE int)
--ACTOR(ACTID int, ANAME char(30), SEX char(2), BYEAR int)
--ACTIN(ACTID int, FID int, ISLEADING char(1), GRADE int)
--THEATER (TID int, TNAME char(20), TAREA char(20), ADDRESS char(30))
--SHOW(FID int, TID int , PRICE int, YEAR int , MONTH int)
USE lab_1and2;

----请分别用一条SQL语句完成下列各个小题的查询需求：
--1）查询“战狼”这部电影在洪山区各家影院的2017年的上映情况，并按照上映的月份的降序排列； 
SELECT DISTINCT FILM.FNAME,THEATER.TNAME,SHOW.MONTH,SHOW.PRICE
FROM FILM,SHOW, THEATER
WHERE SHOW.TID = THEATER.TID AND SHOW.FID=FILM.FID AND
	FILM.FNAME='战狼'AND SHOW.YEAR = 2017 AND THEATER.TAREA='洪山区'
ORDER BY SHOW.MONTH DESC;
GO
--2）查询所有无参演演员信息的电影的基本信息，并且将结果按照电影类型的升序排列，相同类型的电影则按照用户评分的降序排列； 
SELECT *
FROM FILM
WHERE FILM.FID NOT IN (
    SELECT DISTINCT ACTIN.FID
FROM ACTIN 
)
ORDER BY FILM.FTYPE,GRADE DESC;
GO
--3）查询所有直到2017年仍未上映的电影编号、电影名称、导演姓名；
SELECT FILM.FID,FNAME,DNAME 
FROM FILM 
WHERE FID IN(
		SELECT FID 
		FROM SHOW 
		GROUP BY FID 
		HAVING MIN(SHOW.YEAR) > 2017
		);

GO
--4）查询在各家电影院均上映过的电影编号；
SELECT DISTINCT SHOW1.FID
FROM SHOW SHOW1
WHERE NOT EXISTS ( 
    SELECT THEATER.TID
FROM THEATER
WHERE THEATER.TID NOT IN ( 
    SELECT TID
FROM SHOW SHOW2
WHERE SHOW1.FID = SHOW2.FID 
        )
    );
GO
--5）查询所有用户评分低于80分或者高于89分的电影编号、电影名称、导演姓名及其用户评分，要求where子句中只能有一个条件表达式；
SELECT FID, FNAME, DNAME, GRADE
FROM FILM
WHERE GRADE NOT BETWEEN 80 AND 90;
GO
--6）查询每个导演所执导的全部影片的最低和最高用户评分； 
SELECT DNAME, MIN(GRADE)AS MIN_GRADE, MAX(GRADE)AS MAX_GRADE
FROM FILM
GROUP BY DNAME;
GO
--7）查询至少执导过2部电影的导演姓名、执导电影数量；
SELECT DNAME, COUNT(FID) AS DNUM
FROM FILM
GROUP BY DNAME
HAVING COUNT(FID) >= 2;

--8）查询至少2部电影的用户评分超过80分的导演及其执导过的影片数量、平均用户评分；
SELECT DNAME, COUNT(FID)AS FILM_NUM, AVG(GRADE)AS AVG_GRADE
FROM FILM F1
GROUP BY DNAME
HAVING (SELECT COUNT(*)
FROM FILM F2
WHERE F1.DNAME = F2.DNAME AND
    F2.GRADE >= 80 ) >=2;

--9）查询至少执导过2部电影的导演姓名以及跟这些导演合作过的演员编号、姓名；
SELECT DISTINCT F1.DNAME,ACTOR.ACTID,ACTOR.ANAME
FROM FILM F1,ACTIN,ACTOR
WHERE ACTIN.FID = F1.FID AND ACTIN.ACTID = ACTOR.ACTID
	AND (SELECT COUNT(*)
	FROM FILM F2
	WHERE F1.DNAME = F2.DNAME) >=2
	AND F1.DNAME!=ACTOR.ANAME;--自导自演不算
    

--10）查询每个演员担任主角的电影中的平均用户评分； 
SELECT ACTIN.ACTID,ANAME,AVG(GRADE) AS AVG_GRADE
FROM ACTIN,ACTOR
WHERE ACTIN.ACTID = ACTOR.ACTID AND
	ACTIN.ISLEADING='Y'
GROUP BY ACTIN.ACTID,ANAME;

--11）查询用户评分超过90分的电影的最早上映年月； 
SELECT DISTINCT FILM.FNAME,FILM.GRADE,YEAR,MONTH
FROM FILM,SHOW S1
WHERE FILM.FID=S1.FID AND
	FILM.GRADE>90 AND
	NOT EXISTS (
	SELECT *
	FROM SHOW S2
	WHERE S1.FID=S2.FID AND
	S1.YEAR > S2.YEAR OR (S1.YEAR = S2.YEAR AND S1.MONTH>S2.MONTH)
	);


--12）查询用户评分超过90分的电影的最早上映年月及其相应的上映影院编号； 
SELECT DISTINCT FILM.FNAME,FILM.GRADE,YEAR,MONTH,TID
FROM FILM,SHOW S1
WHERE FILM.FID=S1.FID AND
	FILM.GRADE>90 AND
	NOT EXISTS (
	SELECT *
	FROM SHOW S2
	WHERE S1.FID=S2.FID AND
	S1.YEAR > S2.YEAR OR (S1.YEAR = S2.YEAR AND S1.MONTH>S2.MONTH)
	)


--13）查询每个电影的上映总次数；
SELECT FILM.FID,FNAME,COUNT(SHOW.TID)AS SHOW_TIMES
FROM FILM  LEFT JOIN SHOW 
ON FILM.FID=SHOW.FID
GROUP BY FILM.FID,FNAME

--14）查询执导过动作片，或者警匪片，或者枪战片的导演的姓名，要求where子句中只能有一个条件表达式；
SELECT DISTINCT DNAME
FROM FILM
WHERE FTYPE IN('动作','警匪','枪战');

--15）查询所有“战狼”系列的电影的编号、电影名称、上映电影院名称及其上映年月，结果按照电影名称的升序排列；
SELECT FILM.FID,FILM.FNAME,THEATER.TNAME,SHOW.YEAR,SHOW.MONTH
FROM FILM,SHOW,THEATER
WHERE FILM.FID = SHOW.FID AND SHOW.TID = THEATER.TID
	AND FILM.FNAME LIKE '战狼%'
ORDER BY FILM.FNAME

--16）查询在同一个年月上映1号和2号电影的影院编号；
SELECT DISTINCT TID
FROM SHOW S1
WHERE S1.FID = 1 AND 
	EXISTS (
	SELECT * 
	FROM SHOW S2
	WHERE S2.TID = S1.TID AND 
		S2.FID = 2 AND
		S2.YEAR = S1.YEAR AND
		S2.MONTH = S1.MONTH )
	
--17）查询所有没参演过用户评分85分以下电影的演员的编号、姓名；
SELECT ACTID,ANAME 
FROM ACTOR
WHERE NOT EXISTS(
	SELECT * 
	FROM ACTIN,FILM
	WHERE ACTIN.FID = FILM.FID AND ACTIN.ACTID=ACTOR.ACTID AND
		FILM.GRADE < 85)

--18）查询参演过“吴宇森”执导过的所有电影的演员姓名；
SELECT DISTINCT ANAME
FROM ACTOR,ACTIN A1
WHERE A1.ACTID = ACTOR.ACTID AND 
	NOT EXISTS (
	SELECT *
	FROM FILM
	WHERE DNAME = '吴宇森' AND
		NOT EXISTS (
		SELECT *
		FROM ACTIN A2
		WHERE A2.FID=FILM.FID AND
			A2.ACTID = A1.ACTID
		)
	)

--19）查询所有的演员的编号、姓名及其参演过的电影名称，要求即使该演员未参演过任何电影也要能够输出其编号、姓名；
SELECT ACTOR.ACTID,ACTOR.ANAME,FNAME
FROM ACTOR LEFT JOIN (
			ACTIN LEFT JOIN FILM 
			ON ACTIN.FID = FILM.FID) 
		ON ACTOR.ACTID = ACTIN.ACTID;


--20）查询所有上映超过3次但没有用户评分的电影编号、名称。
SELECT FILM.FID,FNAME
FROM FILM
WHERE GRADE IS NULL AND
	FILM.FID IN (SELECT SHOW.FID
		FROM SHOW
		GROUP BY SHOW.FID
		HAVING COUNT(*)>3
		)
